"""Probabilistic ensemble forecasting using acidwg_py outputs.

NEW feature — not in original rSWAT R package.

Takes 1000 ensemble weather inputs generated by acidwg_py,
runs SWAT-Plus for each member (parallel), collects streamflow outputs,
and computes probabilistic forecast statistics:
  - Quantile ensemble (Q10, Q25, Q50, Q75, Q90)
  - Exceedance probability curves
  - Ensemble spread (min / max / std)
"""

from __future__ import annotations

import shutil
import tempfile
from concurrent.futures import ProcessPoolExecutor, as_completed
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np
import pandas as pd

from swat_py.config.env import EnvConfig
from swat_py.io.station import load_station_csv
from swat_py.io.weather_swat_plus import write_all_weather_plus
from swat_py.io.config_swat_plus import write_time_sim, patch_print_prt
from swat_py.output.reader_swat_plus import parse_channel_sd_day, extract_cha_outtype
from swat_py.output.aggregator import add_date_parts
from swat_py.runner.executor import SwatExecutor
from swat_py.runner.file_manager import setup_run_dir


@dataclass
class EnsembleConfig:
    """Configuration for the acidwg_py ensemble forecast run.

    Parameters
    ----------
    ensemble_dir:
        Root directory of acidwg_py outputs. Expected structure:
        ``ensemble_dir/member_001/``, ``ensemble_dir/member_002/``, ...
        Each member directory contains daily weather CSVs per station.
    n_members:
        Number of ensemble members to process (default 1000).
    parallel:
        Run members in parallel using a process pool.
    n_workers:
        Number of worker processes for parallel execution.
    out_types:
        SWAT-Plus output types to extract (default ``["flow"]``).
    quantiles:
        Quantile levels for probabilistic output (default deciles).
    """

    ensemble_dir: str = ""
    n_members: int = 1000
    parallel: bool = True
    n_workers: int = 4
    out_types: List[str] = field(default_factory=lambda: ["flow"])
    quantiles: List[float] = field(
        default_factory=lambda: [0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95]
    )


# ── internal helpers ──────────────────────────────────────────────────────────

def _discover_members(ensemble_dir: Path, n_members: int) -> List[Path]:
    """Return sorted list of member subdirectories."""
    candidates = sorted(
        [d for d in ensemble_dir.iterdir() if d.is_dir()]
    )
    return candidates[:n_members]


def _run_one_member(
    member_dir: Path,
    base_run_dir: Path,
    stations,
    cfg: EnvConfig,
    syear: int,
    eyear: int,
    exe_name: str,
) -> Optional[pd.DataFrame]:
    """Set up and run one ensemble member; return daily flow DataFrame."""
    nyskip = int(cfg.CioNYSKIP)

    # Create isolated temp run dir
    tmp_dir = Path(tempfile.mkdtemp(prefix=f"swat_py_ens_{member_dir.name}_"))
    try:
        # Copy TxtInOut base (SWAT-Plus input files) to tmp_dir
        for f in base_run_dir.iterdir():
            if f.is_file():
                shutil.copy2(f, tmp_dir / f.name)

        # Write member-specific weather inputs
        write_all_weather_plus(
            stations=stations,
            wthr_dir=member_dir,
            out_dir=tmp_dir,
            fnamestr=None,
        )

        # Update time.sim / print.prt
        nbyr = eyear - syear + 1 + nyskip
        iyr = syear - nyskip
        write_time_sim(tmp_dir, nbyr, iyr)
        patch_print_prt(tmp_dir, nbyr, iyr, nyskip)

        # Run SWAT-Plus
        SwatExecutor(tmp_dir, exe_name).run()

        # Parse output
        sdate = f"{syear}-01-01"
        for otype in cfg.OutputTypes:
            cha_path = tmp_dir / f"channel_{otype}_day.txt"
            if cha_path.exists():
                for outlet in cfg.OutletFlowIDs:
                    raw = parse_channel_sd_day(cha_path, outlet, sdate)
                    if raw is not None:
                        return extract_cha_outtype(raw, "flow")

        return None
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)


# ── public API ────────────────────────────────────────────────────────────────

def run_ensemble_forecast(
    cfg: EnvConfig,
    ens_cfg: EnsembleConfig,
    syear: int,
    eyear: int,
    exe_name: str = "SWAT-Plus.exe",
) -> Dict[str, pd.DataFrame]:
    """Run all ensemble members and return probabilistic forecast results.

    Parameters
    ----------
    cfg:       Main swat_py environment configuration.
    ens_cfg:   Ensemble-specific configuration.
    syear:     Forecast start year.
    eyear:     Forecast end year.
    exe_name:  SWAT-Plus executable name.

    Returns
    -------
    dict with keys:
      - ``"ensemble"``    : wide DataFrame (date × member_id)
      - ``"quantiles"``   : date × quantile level
      - ``"exceedance"``  : date × exceedance probability
      - ``"spread"``      : date × (min, max, std, mean)
    """
    ensemble_dir = Path(ens_cfg.ensemble_dir)
    base_run_dir = Path(cfg.SwatRunDir)
    out_dir = Path(cfg.SwatFcstDir) / "Ensemble"
    setup_run_dir(out_dir)

    stations = load_station_csv(
        Path(cfg.ObsDayDir) / cfg.StnFile,
        cfg.StnIDs,
    )
    members = _discover_members(ensemble_dir, ens_cfg.n_members)

    print(f"[Ensemble] Running {len(members)} members "
          f"({'parallel' if ens_cfg.parallel else 'sequential'}, "
          f"workers={ens_cfg.n_workers})")

    member_results: Dict[str, pd.Series] = {}

    if ens_cfg.parallel:
        with ProcessPoolExecutor(max_workers=ens_cfg.n_workers) as pool:
            futures = {
                pool.submit(
                    _run_one_member,
                    m, base_run_dir, stations, cfg, syear, eyear, exe_name,
                ): m.name
                for m in members
            }
            for fut in as_completed(futures):
                name = futures[fut]
                try:
                    result = fut.result()
                    if result is not None:
                        member_results[name] = result.set_index("date")["flow_cms"]
                except Exception as exc:
                    print(f"[WARN] Member {name} failed: {exc}")
    else:
        for m in members:
            result = _run_one_member(
                m, base_run_dir, stations, cfg, syear, eyear, exe_name
            )
            if result is not None:
                member_results[m.name] = result.set_index("date")["flow_cms"]

    if not member_results:
        raise RuntimeError("No ensemble members produced valid output.")

    # Build wide DataFrame
    ensemble_df = pd.DataFrame(member_results)
    ensemble_df.index.name = "date"
    ensemble_df = ensemble_df.sort_index()

    # Compute statistics
    quantile_df = ensemble_df.quantile(ens_cfg.quantiles, axis=1).T
    quantile_df.columns = [f"Q{int(q*100)}" for q in ens_cfg.quantiles]

    spread_df = pd.DataFrame({
        "mean": ensemble_df.mean(axis=1),
        "std":  ensemble_df.std(axis=1),
        "min":  ensemble_df.min(axis=1),
        "max":  ensemble_df.max(axis=1),
    })

    # Exceedance probability for each date
    # P(Q > q) estimated from empirical distribution across members
    def _exceedance_row(row: pd.Series) -> pd.Series:
        sorted_vals = np.sort(row.dropna().values)[::-1]  # descending
        n = len(sorted_vals)
        exc_probs = (np.arange(1, n + 1)) / (n + 1)
        return pd.Series(sorted_vals, index=[f"{p:.3f}" for p in exc_probs])

    exceedance_df = ensemble_df.apply(_exceedance_row, axis=1)

    # Save outputs
    ensemble_df.reset_index().to_csv(out_dir / "ensemble_flow.csv", index=False)
    quantile_df.reset_index().to_csv(out_dir / "quantile_flow.csv")
    spread_df.reset_index().to_csv(out_dir / "spread_flow.csv")
    exceedance_df.reset_index().to_csv(out_dir / "exceedance_flow.csv")

    print(f"[Ensemble] Results saved to {out_dir}")

    return {
        "ensemble":   ensemble_df.reset_index(),
        "quantiles":  quantile_df.reset_index(),
        "exceedance": exceedance_df.reset_index(),
        "spread":     spread_df.reset_index(),
    }


def plot_ensemble_forecast(
    results: Dict[str, pd.DataFrame],
    outlet_nm: str = "",
    out_path: Optional[Path] = None,
) -> None:
    """Plot ensemble fan chart (quantile shading + median line).

    Parameters
    ----------
    results:    dict returned by :func:`run_ensemble_forecast`.
    outlet_nm:  Outlet name for the title.
    out_path:   If provided, save the figure to this path.
    """
    import matplotlib.pyplot as plt

    q_df = results["quantiles"].copy()
    q_df["date"] = pd.to_datetime(q_df["date"])
    q_df = q_df.set_index("date")

    fig, ax = plt.subplots(figsize=(12, 5))

    q_cols = [c for c in q_df.columns if c.startswith("Q")]
    # Shade between Q10-Q90, Q25-Q75
    if "Q10" in q_cols and "Q90" in q_cols:
        ax.fill_between(q_df.index, q_df["Q10"], q_df["Q90"],
                        alpha=0.2, color="steelblue", label="Q10-Q90")
    if "Q25" in q_cols and "Q75" in q_cols:
        ax.fill_between(q_df.index, q_df["Q25"], q_df["Q75"],
                        alpha=0.4, color="steelblue", label="Q25-Q75")
    if "Q50" in q_cols:
        ax.plot(q_df.index, q_df["Q50"], color="steelblue",
                linewidth=2, label="Median (Q50)")

    ax.set_ylabel("streamflow (cms)")
    ax.set_xlabel("Date")
    ax.set_title(f"Ensemble Probabilistic Forecast — {outlet_nm}")
    ax.legend(fontsize=8, frameon=False)

    if out_path:
        fig.savefig(out_path, dpi=200, bbox_inches="tight")
        plt.close(fig)
    else:
        plt.show()
